CREATE TABLE [dbo].[Pedidos] (
    [PedidoID]                INT             IDENTITY (1, 1) NOT NULL,
    [NumeroPedido]            VARCHAR (20)    NOT NULL,
    [UsuarioID]               INT             NOT NULL,
    [EstadoID]                INT             NOT NULL,
    [CarritoID]               INT             NULL,
    [NombreFacturacion]       VARCHAR (100)   NULL,
    [DireccionFacturacion]    VARCHAR (255)   NULL,
    [CiudadFacturacion]       VARCHAR (100)   NULL,
    [DepartamentoFacturacion] VARCHAR (100)   NULL,
    [TelefonoFacturacion]     VARCHAR (20)    NULL,
    [NombreEnvio]             VARCHAR (100)   NULL,
    [DireccionEnvio]          VARCHAR (255)   NULL,
    [CiudadEnvio]             VARCHAR (100)   NULL,
    [DepartamentoEnvio]       VARCHAR (100)   NULL,
    [TelefonoEnvio]           VARCHAR (20)    NULL,
    [SubTotal]                DECIMAL (10, 2) NOT NULL,
    [ImpuestosTotal]          DECIMAL (10, 2) NOT NULL,
    [CostoEnvio]              DECIMAL (10, 2) NOT NULL,
    [DescuentoTotal]          DECIMAL (10, 2) DEFAULT ((0)) NULL,
    [Total]                   DECIMAL (10, 2) NOT NULL,
    [MetodoPago]              VARCHAR (50)    NULL,
    [EstadoPago]              VARCHAR (50)    NULL,
    [ReferenciaPago]          VARCHAR (100)   NULL,
    [MetodoEnvio]             VARCHAR (50)    NULL,
    [NumeroGuia]              VARCHAR (50)    NULL,
    [EmpresaEnvio]            VARCHAR (100)   NULL,
    [FechaCreacion]           DATETIME        DEFAULT (getdate()) NULL,
    [FechaActualizacion]      DATETIME        NULL,
    [FechaPago]               DATETIME        NULL,
    [FechaEnvio]              DATETIME        NULL,
    [FechaEntrega]            DATETIME        NULL,
    [Notas]                   TEXT            NULL,
    [NotasInternas]           TEXT            NULL,
    [CreadoPor]               INT             NULL,
    [IP]                      VARCHAR (50)    NULL,
    [UserAgent]               VARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([PedidoID] ASC),
    FOREIGN KEY ([CarritoID]) REFERENCES [dbo].[Carritos] ([CarritoID]),
    FOREIGN KEY ([EstadoID]) REFERENCES [dbo].[EstadosPedido] ([EstadoID]),
    FOREIGN KEY ([UsuarioID]) REFERENCES [dbo].[Usuarios] ([UsuarioID]),
    UNIQUE NONCLUSTERED ([NumeroPedido] ASC)
);


GO

