[resolvers]
"@/*" = "./src/*"
"@config/*" = "./src/config/*"
"@controllers/*" = "./src/controllers/*"
"@models/*" = "./src/models/*"
"@routes/*" = "./src/routes/*"
"@middleware/*" = "./src/middleware/*"
"@services/*" = "./src/services/*"
"@utils/*" = "./src/utils/*"